export const GET_WISHLIST = "GET_WISHLIST";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const GET_WISHLIST_FAILURE = "GET_WISHLIST_FAILURE";
// -------------------------------------------------------------
export const POST_ADD_PRODUCT_TO_WISHLIST = "POST_ADD_PRODUCT_TO_WISHLIST";
export const POST_ADD_PRODUCT_TO_WISHLIST_SUCCESS =
  "POST_ADD_PRODUCT_TO_WISHLIST_SUCCESS";
export const POST_ADD_PRODUCT_TO_WISHLIST_FAILURE =
  "POST_ADD_PRODUCT_TO_WISHLIST_FAILURE";
// -------------------------------------------------------------
export const EDIT_WISHLIST = "EDIT_WISHLIST";
export const EDIT_WISHLIST_SUCCESS = "EDIT_WISHLIST_SUCCESS";
export const EDIT_WISHLIST_FAILURE = "EDIT_WISHLIST_FAILURE";
// -------------------------------------------------------------
export const DELETE_PRODUCT_FROM_WISHLIST = "DELETE_PRODUCT_FROM_WISHLIST";
export const DELETE_PRODUCT_FROM_WISHLIST_SUCCESS =
  "DELETE_PRODUCT_FROM_WISHLIST_SUCCESS";
export const DELETE_PRODUCT_FROM_WISHLIST_FAILURE =
  "DELETE_PRODUCT_FROM_WISHLIST_FAILURE";
